### ISSUE TITLE
How do I move backwards?

### ISSUE THREAD

**Issue by yummyduckie** [disheng222/SP3#1]
How do I move backwards? In Scratch programming I was able to move backwards by switching the motor pair order, but I don't think it works with Python. I can only move in one direction but for some missions I would need to move in the other direction. @disheng222

**Comment by disheng222** [comment]
Please check this code:
https://github.com/disheng222/SP3/blob/main/GyroMoveStopBySeconds.py
See line 26-32. Feel free to let me know if you still have the question.

**Comment by disheng222** [comment]
Please note that this function def gyroMoveStopbySeconds(motorPair,
direction, speed, seconds) (in GyroMoveStopBySeconds.py) allows you to set
a negative direction, such as -45, right? Did I answer your question?

**Comment by yummyduckie** [comment]
I tried to run it with a negative direction and it works. I'm going to close this issue. Thank you!
